### ISSUE TITLE
Some key inputs are used as controller on Arturia Keylab Essential 49

### ISSUE THREAD

**Issue by DahliaSager** [tfraudet/Reason-ArturiaKeylabEssential-Remote#9]
Thank you for these remote scripts! I'm using Arturia Keylab Essential 49, and it seems that when D3 is pressed together with another key, the function of undo will be triggered. Also, some of the controller buttons on the keyboard trigger the MIDI for pitched notes when I'm playing with the instruments in the rack.

**Comment by tfraudet** [comment]
Hi @DahliaSager , not sure why you have this behavior. Did you defined specific remote overrides for undo/redo ? (see "Additional Remote Overrides" reason.
![Screenshot 2021-02-28 at 13 54 09](https://user-images.githubusercontent.com/34861241/109419328-2753ec00-79cd-11eb-911c-b863faef15a9.png)
on menu)

**Comment by tfraudet** [comment]
which controller buttons are they? the default behaviour of the pads is to trigger notes between (C1 to G1) .

**Comment by fjb751115** [comment]
Hi Thierry

Thank you for the amazing work you have done to control Reason. Is there a way to set the controllers to use "Pickup" rather than "Jump"? I noted with Mackie control this can be set. Is there a way to not have the faders jump using your config. When you move between instruments the controller forces last used position to the new instance.

**Comment by tfraudet** [comment]
Hi @fjb751115 , see https://github.com/tfraudet/Reason-ArturiaKeylabEssential-Remote/issues/10
